name = "funny-web"
compatibility_date = "2023-12-01"
compatibility_flags = ["nodejs_compat"]
main = ".vercel/output/static/_worker.js"

[site]
bucket = ".vercel/output/static"

[build]
command = "npm run pages:build" 